### ISSUE TITLE
bug: 事件监听出现的问题

### ISSUE THREAD

**Issue by alexzhang1030** [zxTick/ztcanvas#15]
由于内部实现以及 canvas 自身的问题，在通过滚动事件或其他事件修改了 canvas 的位置时，内部的 click 监听事件需要实时修改 path2d 的 x 和 y 值，否则通过事件对象读出来的 x 和 y 是肯定无法匹配到 path2d 中的 x 和 y 的。

详细复现：

- [点击事件例子](https://ztcanvas.netlify.app/guide/why.html#with-event-listener)

滚动修改 canvas 位置，那么将不再触发。除非重新渲染

**Comment by TickHeart** [comment]
scroll，resize事件可以解决吧

**Comment by alexzhang1030** [comment]
yeah
